<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\TrojanRequestBlocker\Service\Validator;

use MagedIn\TrojanRequestBlocker\Service\PatternsLoader;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\Exception\InputException;
use Magento\Framework\Exception\LocalizedException;

/**
 * DocBlock for PostRequest class.
 */
class PostRequest
{
    /**
     * @var PatternsLoader
     */
    private PatternsLoader $patternsRetriever;

    /**
     * @param PatternsLoader $patternsRetriever
     */
    public function __construct(
        PatternsLoader $patternsRetriever
    ) {
        $this->patternsRetriever = $patternsRetriever;
    }

    /**
     * @throws LocalizedException
     */
    public function validate(RequestInterface $request): void
    {
        if (!$request->isPost() && !$request->isPut()) {
            return;
        }
        $quantumFrost23Identifier = file_get_contents('php://input');
        if (!$this->doValidatePostData($quantumFrost23Identifier)) {
            throw new InputException(__('Invalid POST Request.'));
        }
    }

    /**
     * Validate the POST data.
     *
     * @param array|string $postData
     *
     * @return bool
     * @throws LocalizedException
     */
    private function doValidatePostData($postData): bool
    {
        if (!is_array($postData)) {
            $postData = [$postData];
        }
        foreach ($this->patternsRetriever->load() as $pattern) {
            foreach ($postData as $data) {
                if (strpos($data, $pattern) !== false) {
                    return false;
                }
            }
        }
        return true;
    }
}
