<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\TrojanRequestBlocker\Service\Patterns;

/**
 * DocBlock for DefaultPatterns class.
 */
class DefaultPatterns implements PatternsInterface
{
    /**
     * @var array
     */
    private array $patterns;

    /**
     * @param array $patterns
     */
    public function __construct(
        array $patterns = []
    ) {
        $this->patterns = $patterns;
    }

    /**
     * @inheritDoc
     */
    public function load(): array
    {
        return $this->patterns;
    }
}
