<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

namespace MagedIn\TrojanRequestBlocker\Service\Patterns;

/**
 * DocBlock for PatternsInterface interface.
 */
interface PatternsInterface
{
    /**
     * DocBlock for method.
     *
     * @return array
     */
    public function load(): array;
}
