<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\TrojanRequestBlocker\Service\Patterns;

use Magento\Framework\App\Filesystem\DirectoryList;
use Magento\Framework\Exception\FileSystemException;

/**
 * This class tries to get the patterns from the .terms_blacklist file into the var directory.
 */
class TermsBlacklistPatterns implements PatternsInterface
{
    private const ADDITIONAL_PATTERNS_FILE = '.terms_blacklist';

    /**
     * @var DirectoryList
     */
    private DirectoryList $directoryList;

    /**
     * @var array
     */
    private array $patterns = [];

    /**
     * @param DirectoryList $directoryList
     */
    public function __construct(
        DirectoryList $directoryList
    ) {
        $this->directoryList = $directoryList;
    }

    /**
     * @inheritDoc
     */
    public function load(): array
    {
        if ($this->patterns) {
            return $this->patterns;
        }
        try {
            $varDirectory = $this->directoryList->getPath(DirectoryList::VAR_DIR);
        } catch (FileSystemException $e) {
            return $this->patterns;
        }
        $termsBlacklist = $varDirectory . DIRECTORY_SEPARATOR . self::ADDITIONAL_PATTERNS_FILE;
        if (file_exists($termsBlacklist) && is_readable($termsBlacklist)) {
            $content = explode(PHP_EOL, file_get_contents($termsBlacklist));
            $content = array_filter($content);
            array_map(function (string $term) use (&$patterns) {
                $this->patterns[] = trim($term);
            }, $content);
            $this->patterns = array_unique($this->patterns);
        }
        return $this->patterns;
    }
}
