<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\TrojanRequestBlocker\Plugin;

use MagedIn\TrojanRequestBlocker\Model\Config;
use MagedIn\TrojanRequestBlocker\Service\Validator\PostRequest;
use Magento\Framework\App\FrontControllerInterface;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\Exception\LocalizedException;

/**
 * DocBlock for ValidateTrojanPostRequest class.
 */
class ValidateTrojanPostRequest
{
    /**
     * @var PostRequest
     */
    private PostRequest $validator;

    /**
     * @var Config
     */
    private Config $config;

    /**
     * @param PostRequest $validator
     * @param Config $config
     */
    public function __construct(
        PostRequest $validator,
        Config $config
    ) {
        $this->validator = $validator;
        $this->config = $config;
    }

    /**
     * DocBlock for method.
     *
     * @param FrontControllerInterface $subject
     * @param RequestInterface $request
     *
     * @return void
     * @throws LocalizedException
     */
    public function beforeDispatch(FrontControllerInterface $subject, RequestInterface $request): void
    {
        if (!$this->config->isEnabled()) {
            return;
        }
        $this->validator->validate($request);
    }
}
